[tool.poetry]
name = "homework-20-1"
version = "0.1.0"
description = ""
authors = ["Kirillov_Ivan <kirillovio@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
